apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-express-app
  description: A simple Node.js application using the Express framework.
  owner: your-username
  tags:
    - nodejs
    - express
    - backend
spec:
  type: service
  lifecycle: production
  owner: team-name
  system: your-system
  repository: https://github.com/Anirudh-Brillio/realtor-backend
  
